In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/automobileEDA.csv"

In [31]:
df = pd.read_csv(filename)
df

symboling  normalized-losses         make aspiration num-of-doors  \
0            3                122  alfa-romero        std          two   
1            3                122  alfa-romero        std          two   
2            1                122  alfa-romero        std          two   
3            2                164         audi        std         four   
4            2                164         audi        std         four   
..         ...                ...          ...        ...          ...   
196         -1                 95        volvo        std         four   
197         -1                 95        volvo      turbo         four   
198         -1                 95        volvo        std         four   
199         -1                 95        volvo      turbo         four   
200         -1                 95        volvo      turbo         four   

      body-style drive-wheels engine-location  wheel-base    length  ...  \
0    convertible          rwd           front        88.6  0.811148  ...   
1    convertible          rwd           front        88.6  0.811148  ...   
2      hatchback          rwd           front        94.5  0.822681  ...   
3          sedan          fwd           front        99.8  0.848630  ...   
4          sedan          4wd           front        99.4  0.848630  ...   
..           ...          ...             ...         ...       ...  ...   
196        sedan          rwd           front       109.1  0.907256  ...   
197        sedan          rwd           front       109.1  0.907256  ...   
198        sedan          rwd           front       109.1  0.907256  ...   
199        sedan          rwd           front       109.1  0.907256  ...   
200        sedan          rwd           front       109.1  0.907256  ...   

     compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                  9.0       111.0    5000.0       21          27  13495.0   
1                  9.0       111.0    5000.0       21          27  16500.0   
2                  9.0       154.0    5000.0       19          26  16500.0   
3                 10.0       102.0    5500.0       24          30  13950.0   
4                  8.0       115.0    5500.0       18          22  17450.0   
..                 ...         ...       ...      ...         ...      ...   
196                9.5       114.0    5400.0       23          28  16845.0   
197                8.7       160.0    5300.0       19          25  19045.0   
198                8.8       134.0    5500.0       18          23  21485.0   
199               23.0       106.0    4800.0       26          27  22470.0   
200                9.5       114.0    5400.0       19          25  22625.0   

    city-L/100km  horsepower-binned  diesel  gas  
0      11.190476             Medium       0    1  
1      11.190476             Medium       0    1  
2      12.368421             Medium       0    1  
3       9.791667             Medium       0    1  
4      13.055556             Medium       0    1  
..           ...                ...     ...  ...  
196    10.217391             Medium       0    1  
197    12.368421               High       0    1  
198    13.055556             Medium       0    1  
199     9.038462             Medium       1    0  
200    12.368421             Medium       0    1  

[201 rows x 29 columns]

In [32]:
# Simple Linear Regression
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [40]:
# Select the X [Predictor] and Y [Target Variable]

X = df[['highway-mpg']]
Y = df['price']

In [41]:
# Splitting the data into training set and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3, random_state=42)

In [ ]:
# Training the model

In [42]:
lm.fit(X_train, Y_train)

LinearRegression()

In [43]:
# Coefficient for each of the variables - Slope of the line
# Higher the coef, higher is the impact 
lm.coef_

array([-765.14074509])

In [44]:
predictions = lm.predict(X_test)
predictions

array([ 7814.48806726, 19291.59924365,  7049.34732217, 10109.91030254,
       14700.75477309,  4753.92508689, 22352.16222402, 11640.19179273,
       17761.31775346, 21587.02147892, 16996.17700837,  3988.7843418 ,
       13170.47328291, 11640.19179273, 17761.31775346,   928.22136143,
       11640.19179273,  7814.48806726, 11640.19179273, 22352.16222402,
       16996.17700837, 20821.88073383,  7049.34732217,  7814.48806726,
       16996.17700837,  3988.7843418 , 13170.47328291, 16996.17700837,
       16996.17700837, 16231.03626328, 13935.614028  ,  3223.64359671,
       18526.45849856,  7049.34732217, 11640.19179273, 17761.31775346,
       12405.33253782,  7814.48806726, 13170.47328291, 13170.47328291,
       17761.31775346, 18526.45849856, 10875.05104763,  7049.34732217,
       15465.89551819, 14700.75477309, -5192.9045993 ,  3223.64359671,
       12405.33253782,  7814.48806726, 17761.31775346, 17761.31775346,
       16996.17700837, 12405.33253782,  7049.34732217,  4753.92508689,
      

In [47]:
# To find intercept of the line
lm.intercept_

36124.695635678276

In [55]:
# Multiple Regression
from sklearn.model_selection import train_test_split
# Selecting the columns and assign it to X and Y
X = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]    
y = df['price']

In [56]:
# Splitting the data into training set and testing set
X_train1, X_test1, y_train1, y_test1 = train_test_split(X,y, test_size=0.3, random_state=42)

In [ ]:
# Training the model

In [57]:
from sklearn.linear_model import LinearRegression

In [58]:
lm1 = LinearRegression()

In [59]:
lm1.fit(X_train1, y_train1)

LinearRegression()

In [60]:
# SLope of the line
lm1.coef_

array([  22.21002149,    3.45961207,   87.00770438, -102.18020658])

In [61]:
# Intercept of the line
lm1.intercept_

-6126.554647525634

In [62]:
# Predictions
predictions = lm1.predict(X_test1)
predictions

array([ 7011.91754831, 25545.80372293,  5976.30228949,  7884.34468685,
       13179.08303774,  5660.56768373, 28585.22825914, 11613.44418448,
       20309.44129937, 32355.75560675, 22064.52690905,  7554.74584689,
       14912.99687184, 11227.07746071, 14903.29826601,  6590.00717678,
       11335.43526259,  7373.68695511, 11355.0831072 , 28775.50692285,
       22330.60014459, 26182.61564454,  6343.44595385,  6883.91190181,
       22946.72798626, 10070.09026684, 11268.69692811, 23015.92022761,
       22482.82307557, 15012.88633559, 10836.03450702,  5348.40438258,
       10131.30002162,  6438.65035006,  7907.92051193, 14464.44544876,
        9058.40017354,  8731.69942914, 14861.10269082,  9021.08426123,
       18015.85638144, 19972.12788619,  9953.35406894,  6212.74076028,
       17039.57853308, 16025.20315919,  3574.91971815,  5469.49080494,
       10683.78066747,  6600.22371228, 17062.56160462, 20171.05681667,
       14268.33780103, 13428.7469505 ,  6136.62929479,  5834.5830925 ,
      

In [ ]:
# Polynomial Regression

In [63]:
# Data Preparations
# Checking for null values
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    1
diesel               0
gas                  0
dtype: int64

In [67]:
# Assign X[Predictors] and Y[Target Variable] variables to columns
X2 = df[["highway-mpg"]]
Y2 = df["price"]

In [68]:
# Split for Training and Testing
from sklearn.model_selection import train_test_split
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(X2,Y2, test_size=0.25, random_state = 1)

In [69]:
# Scalling the data: Bringing the values in the df in the similar range
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train2)
X_test_scaler = scaler.transform(X_test2)

In [ ]:
# Model Development and evaluation 

In [70]:
from sklearn.linear_model import LinearRegression
lin = LinearRegression()

In [71]:
# Training the model [degree = 3]
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3) # degree decides overfitting, underfitting, or good fitting
X_poly_train = poly.fit_transform(X_train_scaler)
X_test_poly = poly.transform(X_test_scaler)
poly.fit(X_poly_train, Y_train2)
lin.fit(X_poly_train, Y_train2)

LinearRegression()

In [72]:
# Prediction model [degree = 3]
Y_pred_test = lin.predict(X_test_poly)
# for evaluating the model
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test2, Y_pred_test)

2811.213294054509

In [73]:
# Prediction [degree = 3]
# Analytical analysis [using training data]
Y_pred_train = lin.predict(X_poly_train)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_train2, Y_pred_train)

3010.582248943567